version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data_data
      - ./pg_data/postgres_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    restart: always
  pg_dump -U postgres -d postgres_db > /var/lib/postgresql/data/postgres_db.sql
